export const restaurantDetails = [
  {
    id: 1,
    restaurantName: 'KFC',
    distance: '10',
    name: 'food1',
    address: 'Worli, Mumbai',
    image: require('./images/food1.png'),
    discount: '20%',
    reviews: '439',
    reviews: '189',
    rating: '4.9',
  },
  {
    id: 2,
    restaurantName: 'Mc Donalds',
    distance: '20',
    name: 'food2',
    address: 'Vidyavihar, Mumbai',
    image: require('./images/food2.png'),
    discount: '20%',
    reviews: '521',
    rating: '4.6',
    price: '699',
  },
  {
    id: 3,
    restaurantName: 'Pizza Hut',
    distance: '30',
    name: 'food3',
    address: 'Kurla, Mumbai',
    image: require('./images/food3.png'),
    discount: '20%',
    reviews: '367',
    rating: '4.5',
    price: '799',
  },
  {
    id: 4,
    restaurantName: 'The French Gourmet',
    distance: '40',
    name: 'food4',
    address: 'Bandra, Mumbai',
    image: require('./images/food4.png'),
    discount: '20%',
    reviews: '323',
    rating: '3.9',
    price: '899',
  },
]

export const categoryImage = [
  {
    id: 1,
    name: 'burger',
    image: require('./category/burger.png'),
    discount: '20%',
  },
  { id: 2, name: 'Ice_cream', image: require('./category/ice_cream.png') },
  { id: 3, name: 'Nugget', image: require('./category/nugget.png') },
  { id: 4, name: 'Pasta', image: require('./category/pasta.png') },
  { id: 5, name: 'pizza', image: require('./category/pizza.png') },
  { id: 6, name: 'Rice', image: require('./category/rice.png') },
  { id: 7, name: 'Shrimp', image: require('./category/shrimp.png') },
]
